// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rise.PhoneBook.ReportApi.DataAccess.Concrete;

#nullable disable

namespace Rise.PhoneBook.ReportApi.DataAccess.Migrations
{
    [DbContext(typeof(ReportContext))]
    [Migration("20230226200739_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rise.PhoneBook.ReportApi.Entities.Concrete.ReportQueueProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ChangedOn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("changed_on");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("Datas")
                        .HasColumnType("jsonb")
                        .HasColumnName("datas");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("filename");

                    b.Property<string>("LastQueueName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("last_queue_name");

                    b.Property<string>("QueueStatus")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("queue_status");

                    b.Property<string>("Queueprocess")
                        .HasColumnType("jsonb")
                        .HasColumnName("queueprocess");

                    b.Property<short?>("State")
                        .HasColumnType("smallint")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.ToTable("report_queue_processes", "report");
                });
#pragma warning restore 612, 618
        }
    }
}
